version: '2'
services:
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./client/:/usr/app
      - /usr/app/node_modules
    ports:
      - "4200:4200" 
      - "49153:49153"
    expose:
      - "4200"
      - "49153"
  server:
    build:
      context: ./server/
    ports:
      - 8080:8080
