version: '2'
services:
  client:
    build:
      context: ./client/
    command: npm start
    volumes:
      - ./server/:/usr/app
    ports:
      - "4200:4200" 
      - "49153:49153"
    expose:
      - "4200"
      - "49153"
